# https://nx.dev/more-concepts/folder-structure
# https://pnpm.io/workspaces
packages:
  - "**/client/"
  - "**/server/"
  - "**/types/"
  - "**/web/"
  - "**/prisma/"
  - "[core]/*"
  - "lib/*"
  - "docs"

catalog:
  typescript: ^5.5.4
  ts-node: ^10.9.2
  "@types/node": ^20.14.12
  # FiveM
  "@citizenfx/client": 2.0.9282-1
  "@citizenfx/server": 2.0.9282-1
  # Bundle
  rollup: ^4.20.0
  tslib: ^2.6.3
  "@rollup/plugin-commonjs": ^26.0.1
  "@rollup/plugin-node-resolve": ^15.2.3
  "@rollup/plugin-typescript": ^11.1.6
  # Database
  "@prisma/client": ^5.18.0
  prisma: ^5.18.0
  # React
  react: ^18.3.1
  react-dom: ^18.3.1
  react-query: ^3.39.3
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@typescript-eslint/eslint-plugin": ^7.15.0
  "@typescript-eslint/parser": ^7.15.0
  "@vitejs/plugin-react": ^4.3.1
  eslint: ^8.57.0
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-react-refresh: ^0.4.7
  tailwindcss: ^3.4.11
  vite: ^5.3.4
  clsx: ^2.1.1
  autoprefixer: ^10.4.20
  postcss: ^8.4.47
  vitest: ^2.1.1
